export const translates = {
  en: {
    latitude: 'Latitude',
    longitude: 'Longitude',
    daysOfWeek: {
      monday: { full: 'Monday', short: 'Mon' },
      tuesday: { full: 'Tuesday', short: 'Tue' },
      wednesday: { full: 'Wednesday', short: 'Wed' },
      thursday: { full: 'Thursday', short: 'Thu' },
      friday: { full: 'Friday', short: 'Fri' },
      saturday: { full: 'Saturday', short: 'Sat' },
      sunday: { full: 'Sunday', short: 'Sun' },
    },
    weather: {
      feelsLike: 'feels like',
      wind: 'wind',
      humidity: 'humidity',
    },
    months: {
      jan: 'January',
      feb: 'February',
      mar: 'March',
      apr: 'April',
      may: 'May',
      jun: 'June',
      jul: 'July',
      aug: 'August',
      sep: 'September',
      oct: 'October',
      nov: 'November',
      dec: 'December',
    },
    searchFormData: {
      errors: {
        incorrectData: 'Incorrect data',
      },
      searchInputPlaceholder: 'Search city',
      buttonText: 'Search',
    },
  },
  ru: {
    latitude: 'Ширина',
    longitude: 'Долгота',
    daysOfWeek: {
      monday: { full: 'Понедельник', short: 'Пн' },
      tuesday: { full: 'Вторник', short: 'Вт' },
      wednesday: { full: 'Среда', short: 'Ср' },
      thursday: { full: 'Четверг', short: 'Чт' },
      friday: { full: 'Пятница', short: 'Пт' },
      saturday: { full: 'Суббота', short: 'Сб' },
      sunday: { full: 'Воскресенье', short: 'Вс' },
    },
    weather: {
      feelsLike: 'ощущается как',
      wind: 'ветер',
      humidity: 'влажность',
    },
    months: {
      jan: 'Января',
      feb: 'Февраля',
      mar: 'Марта',
      apr: 'Апреля',
      may: 'Мая',
      jun: 'Июня',
      jul: 'Июля',
      aug: 'Августа',
      sep: 'Сентября',
      oct: 'Октября',
      nov: 'Ноября',
      dec: 'Декабря',
    },
    searchFormData: {
      errors: {
        incorrectData: 'Неверные данные',
      },
      searchInputPlaceholder: 'Найти город',
      buttonText: 'Поиск',
    },
  },
  be: {
    latitude: 'Шыраты',
    longitude: 'Даўгата',
    daysOfWeek: {
      monday: { full: 'Панядзелак', short: 'Пн' },
      tuesday: { full: 'Аўторак', short: 'Аў' },
      wednesday: { full: 'Серада', short: 'Ср' },
      thursday: { full: 'Чацвер', short: 'Чц' },
      friday: { full: 'Пятніца', short: 'Пт' },
      saturday: { full: 'Субота', short: 'Сб' },
      sunday: { full: 'Нядзеля', short: 'Нд' },
    },
    weather: {
      feelsLike: 'адчуваецца як',
      wind: 'вецер',
      humidity: 'вільготнасць',
    },
    months: {
      jan: 'Студзень',
      feb: 'Лютага',
      mar: 'Сакавік',
      apr: 'Красавік',
      may: 'Май',
      jun: 'Чэрвень',
      jul: 'Ліпеня',
      aug: 'Жнівень',
      sep: 'Верасень',
      oct: 'Кастрычнік',
      nov: 'Лістапада',
      dec: 'Снежні',
    },
    searchFormData: {
      errors: {
        incorrectData: 'Няслушныя дадзеныя',
      },
      searchInputPlaceholder: 'Знайсці горад',
      buttonText: 'Пошук',
    },
  },
};
